name: KitGui
version: ${project.version}
main: me.shane.kitgui.kitgui.KitGui
description: A GUI for the command /kit
softdepend: [Essentials,EssentialsX]
commands:
  kit:
    description: Essentials /kit with gui
    usage: /kit
  kitcfg:
    description: Configurations for /kit GUI
    usage: /kitcfg